version: "1"
volumes:
  data:
    driver:
      local

networks:
  mynetwork:
    driver: bridge

services:
  mongodb:
    container_name: "flemis-mongodb-dev"
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_PORT=${MONGO_PORT}'
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
  mysql:
    container_name: "mysql-dev"
    image: 'mysql:latest'
    volumes:
      - data:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    restart: unless-stopped
  redis:
    image: 'redis:latest'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    environment:
      REDIS_PORT: ${REDIS_PORT}
  api-server:
    container_name: "api-store-container-dev"
    build: ./  #aqui é o caminho do dockerfile
    #image: ibmjava:jre-alpine
    volumes:
      - .m2:/root/.m2
    networks:
      - mynetwork
    links:
     - mysqldb
    environment:
      API_PORT: ${API_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_DRIVER: ${SPRING_DATASOURCE_DRIVER}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: unless-stopped
    depends_on:
      - mysqldb